# Site settings
title: PM2
email: contact@pm2.io
description: > # this means to ignore newlines until "baseurl:"
  Build Battle-Hardened Node.js Applications. Advanced process manager with built-in load balancer, monitoring dashboard, and enterprise solutions. Over 100M downloads, powering modern Node.js applications globally.
baseurl: ""
url: "https://pm2.io"

repo_url: "https://github.com/pm2-hive/pm2-hive.github.io"

sass:
  sass_dir: _sass

markdown: kramdown

exclude:
  ["node_modules", "scripts", "Gemfile", "Gemfile.lock", "README.md", "vendor"]

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

redcarpet:
  extensions: ["tables", "no_intra_emphasis", "autolink"]

permalink: /blog/:year/:month/:day/:title
paginate: 3
register_url: https://id.keymetrics.io/api/oauth/register
login_url: https://id.keymetrics.io/api/oauth/login

# Analytics
mixpanel:
  enabled: true
  token: 0abf6a940a43403982c64ed92aa398dd
  api_host: https://api-eu.mixpanel.com
  dev_mode: false # Set to true to enable debug logging and ignore DNT locally
